### PR TITLE
added category labels to search

### PR DESCRIPTION
**Pull request by RedMan13**
removed all of the {{  }} value getters from toolbox.js and put in place there results since they nolonger serve any purpose

added category labeling to searched blocks and made the search load faster

added back discord-logs to exports package.json

### CODE REVIEW

**Comment by Malix-Labs** [comment]
@RedMan13 just so you know, this is not the correct way an hotfix should be done, I will write some development documentation and file it to you

**Comment by RedMan13** [comment]
> @RedMan13 just so you know, this is not the correct way an hotfix should be done, I will write some development documentation and file it to you

this isnt a hotfix

**Comment by RedMan13** [comment]
ill edit the name so it makes more sense

**Comment by RedMan13** [comment]
done

**Comment by RedMan13** [comment]
@Malix-Off

**Comment by Malix-Labs** [comment]
@RedMan13
> > @RedMan13 just so you know, this is not the correct way an hotfix should be done, I will write some development documentation and file it to you
> 
> this isnt a hotfix

An hotfix is a fix for a problem that happened in the master branch

**Comment by RedMan13** [comment]
> @RedMan13
> 
> > > @RedMan13 just so you know, this is not the correct way an hotfix should be done, I will write some development documentation and file it to you
> > 
> > 
> > this isnt a hotfix
> 
> An hotfix is a fix for a problem that happened in the master branch

ah
not all of this is hotfix theres a hotfix which i think i did correctly
being that there was an issue where discord-logs (something that is imported no matter what) wasnt in the package.json (or atleast thats what i was told)

**Comment by RedMan13** [comment]
*did actually test what i was told

**Pull request merged**
