### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by Malix-Labs**

### CODE REVIEW

**Review by retrouser955 — COMMENTED** [review]
Removed warnings

**Comment by retrouser955** [comment]
@Malix-Off can you get rid of vercel bot for this branch

**Comment by Malix-Labs** [comment]
@retrouser955:
> @Malix-Off can you get rid of vercel bot for this branch

I don't think so, but why would it be turned off?

**Comment by Malix-Labs** [comment]
@retrouser955 is this the release-ready version of v3?

**Comment by retrouser955** [comment]
> @retrouser955 is this the release-ready version of v3?

Not yet, marking it for review was an accident.

**Comment by Malix-Labs** [comment]
@retrouser955 
> > @retrouser955 is this the release-ready version of v3?
> 
> Not yet, marking it for review was an accident.

Then please turn it back to draft

**Pull request closed without merging**
