### PR TITLE
async async :trollface:

### PR DESCRIPTION
**Pull request by RedMan13**

### CODE REVIEW

**Comment by Malix-Labs** [comment]
wdym by

> async async

?

**Comment by RedMan13** [comment]
its just a funny goofy ahh bc im not and duno what to call a async block other then async

**Comment by Malix-Labs** [comment]
- [Comment Reply](https://github.com/scratch-for-discord/Web-Application_Frontend/pull/72#issuecomment-1277074320) from @RedMan13:

  > its just a funny goofy ahh bc im not and duno what to call a async block other then async

So why don't you call it just async

**Comment by RedMan13** [comment]
true

**Pull request merged**
